---
title: "Ordering hypotheses by Oracle lfdr"
author: "Lei Sun"
date: "2018-12-27"
output:
  workflowr::wflow_html:
    code_folding: show
---

```{r}
source("../code/OracleBayesMT.R")
```

```{r}
theta <- c(rep(0, 9e3),
           rep(1, 200),
           rep(2, 200),
           rep(3, 200),
           rep(4, 200),
           rep(5, 200))
theta <- sample(theta)
N <- length(theta)
response <- (theta != 0)
s <- rchisq(N, df = 10)
s <- s / sqrt(mean(s^2))
```

```{r, cache = TRUE}
set.seed(777)
nsim <- 1e3
MTLR.auc <- ODP.auc <- MTLR.z.auc <- pvalue.auc <- BH.auc <- c()
for (i in seq(nsim)) {
  x <- rnorm(N, theta, s)
  
  MTLR <- MTLR.fun(x, theta, s)
  MTLR.auc[i] <- pROC::auc(response, predictor = MTLR)
  
  ODP <- ODP.fun(x, theta, s)
  ODP.auc[i] <- pROC::auc(response, predictor = ODP)
  
  pvalue <- pnorm(-abs(x / s)) * 2
  pvalue.auc[i] <- pROC::auc(response, predictor = pvalue)
  
  BH <- p.adjust(pvalue, method = "BH")
  BH.auc[i] <- pROC::auc(response, predictor = BH)
  
  MTLR.z <- MTLR.fun(x / s, theta / s, rep(1, N))
  MTLR.z.auc[i] <- pROC::auc(response, predictor = MTLR.z)
}

auc.mat <- cbind.data.frame(
  MTLR = MTLR.auc,
  ODP = ODP.auc,
  MTLR.z = MTLR.z.auc,
  pvalue = pvalue.auc,
  BH = BH.auc
)
```

```{r}
barplot(table(theta),
        main = expression(paste("Distribution of ", theta)), cex.main = 2,
        xlab = expression(theta),
        ylab = "Count", cex.lab = 1.5)

hist(s,
     main = expression("Histogram of s"), cex.main = 2,
     cex.lab = 1.5)

boxplot(auc.mat, las = 2, cex.axis = 1,
        main = expression("Distribution of AUC"), cex.main = 2,
        cex.lab = 1.5,
        names = c("MTLR", "ODP", "MTLR.z", "p-value", "BH"))

hist(auc.mat$MTLR - auc.mat$ODP,
     xlim = range(0, auc.mat$MTLR - auc.mat$ODP),
     main = expression("MTLR vs ODP"), cex.main = 2,
     xlab = expression(Delta[AUC]), cex.lab = 1.5)

hist(auc.mat$MTLR - auc.mat$MTLR.z,
     xlim = range(0, auc.mat$MTLR - auc.mat$MTLR.z),
     main = expression("MTLR on X,s vs MTLR on z"), cex.main = 2,
     xlab = expression(Delta[AUC]), cex.lab = 1.5)

hist(auc.mat$MTLR.z - auc.mat$ODP,
     xlim = range(0, auc.mat$MTLR.z - auc.mat$ODP),
     main = expression("MTLR on z vs ODP"), cex.main = 2,
     xlab = expression(Delta[AUC]), cex.lab = 1.5)
```

```{r}
pdf("../figures/theta.pdf", width = 5, height = 5)

par(mar = c(4.5, 4.5, 4.5, 1))

barplot(table(theta),
        main = expression(paste("Distribution of ", theta)), cex.main = 2,
        xlab = expression(theta),
        ylab = "Count", cex.lab = 1.5)

invisible(dev.off())

pdf("../figures/s.pdf", width = 5, height = 5)

par(mar = c(4.5, 4.5, 4.5, 1))

hist(s,
     main = expression("Histogram of s"), cex.main = 2,
     cex.lab = 1.5)

invisible(dev.off())

pdf("../figures/auc.pdf", width = 5, height = 5)

par(mar = c(4.5, 4.5, 4.5, 1))

boxplot(auc.mat, las = 2, cex.axis = 1,
        main = expression("Distribution of AUC"), cex.main = 2,
        cex.lab = 1.5,
        names = c("MTLR", "ODP", "MTLR.z", "p-value", "BH"))

invisible(dev.off())

pdf("../figures/MTLRvsODP.pdf", width = 5, height = 5)

par(mar = c(4.5, 4.5, 4.5, 1))

hist(auc.mat$MTLR - auc.mat$ODP,
     xlim = range(0, auc.mat$MTLR - auc.mat$ODP),
     main = expression("MTLR vs ODP"), cex.main = 2,
     xlab = expression(Delta[AUC]), cex.lab = 1.5)

invisible(dev.off())

pdf("../figures/MTLRvsMTLRz.pdf", width = 5, height = 5)

par(mar = c(4.5, 4.5, 4.5, 1))

hist(auc.mat$MTLR - auc.mat$MTLR.z,
     xlim = range(0, auc.mat$MTLR - auc.mat$MTLR.z),
     main = expression("MTLR on X,s vs MTLR on z"), cex.main = 2,
     xlab = expression(Delta[AUC]), cex.lab = 1.5)

invisible(dev.off())

pdf("../figures/MTLRzvsODP.pdf", width = 5, height = 5)

par(mar = c(4.5, 4.5, 4.5, 1))

hist(auc.mat$MTLR.z - auc.mat$ODP,
     xlim = range(0, auc.mat$MTLR.z - auc.mat$ODP),
     main = expression("MTLR on z vs ODP"), cex.main = 2,
     xlab = expression(Delta[AUC]), cex.lab = 1.5)

invisible(dev.off())
```
